### PR TITLE
OSGi-fying Entire Stack

### PR DESCRIPTION
**Pull request by amitjoy**
Added functionality to make use of OPC-UA Stack library in dynamic
module environment (OSGi)

[Review on Reviewable](https://reviewable.io/reviews/digitalpetri/opc-ua-stack/13)

### CODE REVIEW

**Comment by kevinherron** [comment]
I want to explore the route that netty takes for OSGI compatibility ([see here](https://github.com/netty/netty/blob/master/pom.xml)), which is to use the `maven-bundle-plugin`'s `generate-manifest` goal, and to leave the packaging and dependencies as they are.

**Comment by cdealti** [comment]
@amitjoy can you avoid embedding the jool dependency? Its jar can be osgified separately in the maven build of your osgi project. Or you could submit a PR to the jool repo. It would also simplify the Committer Questionnaire approval if you plan to use Opcua with an Eclipse project.

**Comment by amitjoy** [comment]
@cdealti I have already committed one PR to OSGi-fy **jool** library. For the time-being, I had to embed the dependency and as soon as the jool library gets available in Maven Repo as OSGi Bundle, I would remove the dependency to be embedded in the classpath.

@kevinherron The netty libraries that OPC-UA stack is using are already OSGi-fied and I have already tested the application in my end.

**Comment by kevinherron** [comment]
Closing; this will be implemented as part of the 'osgi' branch.

**Pull request closed without merging**
